apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: starter-api-webmvc
  name: starter-api-webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starter-api-webmvc
  strategy: {}
  template:
    metadata:
      labels:
        app: starter-api-webmvc
    spec:
      hostAliases:
        - ip: 192.168.1.59
          hostnames:
            - "bravo-ch4mp"
      containers:
      - image: starter-api-webmvc:0.0.1-SNAPSHOT
        name: api
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: starter-api
                key: spring.profiles.active
          - name: SERVER_SSL_KEY_STORE
            valueFrom:
              configMapKeyRef:
                name: starter-api
                key: server.ssl.key-store
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: starter-api
                key: spring.datasource.password
          - name: SERVER_SSL_KEY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: starter-api
                key: server.ssl.key.password
          - name: SERVER_SSL_KEY_STORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: starter-api
                key: server.ssl.key-store.password
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /actuator/health/readiness
            port: 4210
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /actuator/health/liveness
            port: 4210
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources: {}

status: {}
